### ISSUE TITLE
Full Text Search Function

### ISSUE THREAD

**Issue by wolf71** [zrzka/blackmamba#21]
Hope add a all file , full text search function. just like quick open (quick open now just search file name,not file contents). using cmd+shift+f key.

**Comment by zrzka** [comment]
For what exactly you need this? My plan is to add smth like open quickly with ability to type func/class/... names. Enough? Or you want reall full text even for markdown files for example?

**Comment by wolf71** [comment]
Full text search for some python comments.

**Comment by zrzka** [comment]
Will think about it. I like [this one](https://github.com/omz/Pythonista-Issues/issues/396) for example, search / list TODOs, ... and other comments. Will this be enough?

**Comment by Phuket2** [comment]
@zrzka, I think a full text search would be great. I had put together one at sometime. Using bits and pieces from other peoples code. When clicking on the file (from the matching criteria) from a list then i displayed a webview and using pygments, displayed the formatted code with the lines hilighted of the matched search criteria. It also handled re expressions (I copied the code). But i found it so useful to find functions/classes I had written before.  Or other code that I had copied from the forum etc. I have so many files because I am constantly testing ang trying new things.

**Comment by Phuket2** [comment]
@zrzka, here is the [gist](https://gist.github.com/05289892bf1042e2097cb32777b6d1bel) to what I did a long time ago. Look i know its a mess.  As i said mostly just copied bits and pieces to get it going. Anyway, just show what I was talking about in the above post

**Comment by zrzka** [comment]
@Phuket2 your link leads to nowhere (404) ...

**Comment by Phuket2** [comment]
Sorry not sure what happened, here is the [gist](https://gist.github.com/Phuket2/05289892bf1042e2097cb32777b6d1be)

**Comment by zrzka** [comment]
Thanks for the input guys, but I'm closing this issue as I have no time to work on this project. I'm looking for a new maintainer/owner (see #39) and then I'll archive this repository if no one will want to continue.
