### ISSUE TITLE
Futurize instead of 2to3 or mondernize

### ISSUE THREAD

**Issue by cclauss** [zrzka/blackmamba#33]
It would be cool if you could add the [futurize](http://python-future.org/futurize_cheatsheet.html) process (at least steps 0 and 1) which is a much more modern, less distructive approach to the 2to3 conversion that is built into Pythonista.

**Comment by zrzka** [comment]
Not sure if this should be included in the Black Mamba. But because it will help to get rid of Python 2, I'll look at it :)

**Comment by cclauss** [comment]
2to3 just move code to 3 often breaking 2 compatibility in the process.  :-(  Futurize focuses on making code run on BOTH.

**Comment by zrzka** [comment]
@cclauss added, see [futurize.py](https://github.com/zrzka/blackmamba/blob/master/blackmamba/script/refactoring/futurize.py). Since I don't use `futurizer` personally, what default arguments should be used? I do use `args = ['-1', '-n', '-w', '--all-imports', '--add-suffix', _SUFFIX, path]` now. Is that okay?

**Comment by zrzka** [comment]
Part of 1.4.1.
