### ISSUE TITLE
ImportError no module named 'blackmamba'

### ISSUE THREAD

**Issue by 368433** [zrzka/blackmamba#34]
I tried to install running:
import requests as r; exec(r.get('http://bit.ly/get-blackmamba').text)

I get
File "<string>", line 217, in _local_installation_exists
ImportError: No module named 'blackmamba'

And:
NameError: name 'ModuleNotFoundError' is not defined.

**Comment by zrzka** [comment]
Aah, thanks. It seems that you have Python 2 as default interpreter. Till I fix installer for Python 2, go to the Pythonista settings, change default interpreter to Python 3, run the installation again. Should work.

**Comment by 368433** [comment]
I just checked, I'm using python 3.5
I reran it with double checking I'm using 3.5 and still get the same message.
I also tried restarting pythonista but get same message. Any idea?

**Comment by zrzka** [comment]
Found it. I forgot that the `ModuleNotFoundError` was introduced in Python 3.6 (Pythonista beta) and you're probably using stable Pythonista version (Python 3.5). Just changed `ModuleNotFoundError` to `ImportError` and it should fix your issue. You'll probably need to kill Pythonista, because of requests caching, so, the request will fetch new installer script from the GitHub.

**Comment by 368433** [comment]
Works like a charm!
Thanks
